### IS727272 - Cordero Hernández, Marco Ricardo

# 6. Numpy

Numpy es un paquete que provee a Python con arreglos multidimensionales (vectores o matrices) de alta eficiencia y diseñados para cálculo científico.

https://numpy.org/

Para utilizar este módulo es necesario importarlo:

In [1]:
import numpy as np

In [2]:
#Array de Zeros
print(np.zeros(20, dtype=int))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [3]:
#Array de unos
print(np.ones(20, dtype=int))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [4]:
#Array de numeros consecutivos que inicien con 0
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [5]:
#Array de numeros que inicien en 2 finalicen en 20 y vayan de 3 en 3
print(np.arange(2, 21, 3))

[ 2  5  8 11 14 17 20]


In [6]:
#Array a partir de una lista
lista = list(range(21))
print(np.array(lista))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [7]:
#Array doble o matriz
l = [[i for i in range(21)], [j for j in range(20, -1, -1)]]
arr = np.array(l)
matr = np.asmatrix(arr)

print(matr)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
 [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]]


In [8]:
#Imprimir las dimensiones del array o la matriz
# print(matr.ndim)
print(matr.shape)

(2, 21)


In [9]:
#Imprimir el tipo del array
print(type(matr))

<class 'numpy.matrix'>


## 6.2 Operaciones con arrays

In [10]:
#Crear dos arrays de dimensión (1,4) de numeros consecutivos
dim_arr = np.arange(4) #.reshape((1,4))
dim_arr_2 = np.arange(4, 8) #.reshape((1,4))

print(dim_arr, dim_arr_2, sep='\n')

[0 1 2 3]
[4 5 6 7]


In [11]:
#Multiplicar el array por una constante
print(np.multiply(dim_arr, 3))
# dim_arr * n es equivalente

[0 3 6 9]


In [12]:
#Sumarle al array una constante a todos los elementos
print(np.add(dim_arr, 20))

[20 21 22 23]


In [13]:
#Formar una matriz con los dos arrays y multiplicarle una constante
#dim_arr_res = np.array([dim_arr, dim_arr_2])
dim_mat = np.matrix([dim_arr, dim_arr_2])

print(np.multiply(dim_mat, 35))

[[  0  35  70 105]
 [140 175 210 245]]


## 6.3 Indexación 


In [14]:
#Crear un array de (0,10) de numeros consecutivos
arr1 = np.arange(11)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [15]:
#Separar los primeros tres elementos del array (slicing)
print(arr1[:3])

[0 1 2]


In [16]:
#Separa del segundo al cuarto elemento del array
print(arr1[2:5])

[2 3 4]


In [17]:
#Hacer una copia del array
arr_copy = arr1.copy()

print(arr_copy)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [18]:
#Asignar el número 20 a los primero 3 elementos del array
arr1[0:3] = 20

print(arr1)

[20 20 20  3  4  5  6  7  8  9 10]


In [19]:
#Hacer una matriz de 3 x 3 e imprimir sus dimensiones
# arr_mult_3 = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_mult_3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# print(arr_mult_3.ndim)
print(arr_mult_3.shape)

(3, 3)


In [20]:
#Imprimir la segunda fila de la matriz
print(arr_mult_3[1])

[4 5 6]


In [21]:
#Imprimir el elemento (1,1) de la matriz
print(arr_mult_3[1][1])

5


## 6.4 Transponer matrices

In [22]:
#Transponer la matriz utilizada en el ejercicio anterior
array_T = arr_mult_3.T
print(array_T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


## 6.5 Funciones con arrays

- Raíz cuadrada
- Números aleatorios
- Suma de vectores


In [23]:
# Raíz cuadrada
array_raiz = np.sqrt(arr_mult_3)

print(array_raiz)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [24]:
# Números aleatorios
array_random = np.random.rand(3, 5)

print(array_random)

[[0.07716542 0.98509275 0.84617261 0.69656483 0.94070702]
 [0.54517095 0.73498841 0.79868697 0.48695764 0.28206482]
 [0.77110995 0.81874619 0.86813891 0.06371143 0.10578533]]


In [25]:
#Suma de vectores o matrices
array_1 = np.arange(15).reshape((3, 5))
print(array_1)

suma = np.add(array_1, array_random)
print(suma)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0.07716542  1.98509275  2.84617261  3.69656483  4.94070702]
 [ 5.54517095  6.73498841  7.79868697  8.48695764  9.28206482]
 [10.77110995 11.81874619 12.86813891 13.06371143 14.10578533]]


## Ejercicio adicional: multiplicación de matrices

In [26]:
# Multiplicar matrices
m = np.matmul(array_1, array_random.T)
print(m)

[[ 8.52996055  4.92149453  3.1692996 ]
 [26.25847368 19.16083848 16.30675863]
 [43.98698682 33.40018242 29.44421765]]


## Ejercicio 1

Crear la funcion "pares" que devuelva un array o vector de números pares entre dos valores que serán parámetros de la función (inicio, fin)

Probar la función "pares" con los números 1 y 30
Probar la función "pares" con los números 2 y 40


In [27]:
#Función pares
def pares(inicio, fin):
    try:
        if(inicio % 2 != 0 or inicio >= fin):
            raise ValueError("Error en parámetros")
        else:
            return np.arange(inicio, fin + 1, 2)
    except ValueError:
        return 'Intenta de nuevo'

In [ ]:
print(pares(1, 30))
print(pares(2, 40))